### ISSUE TITLE
the part number CC2H0ML is incorrect

### ISSUE THREAD

**Issue by jackjliew** [ibm-cloud-docs/ai-openscale-icp#36]
the part number CC2H0ML is incorrect on the following page.
https://cloud.ibm.com/docs/services/ai-openscale-icp?topic=ai-openscale-icp-inst-install-icp#inst-sw

I checked CC2H0ML on IBM internal software download and found it's 
IBM Cloud Pak for Data Enterprise Edition V2.1.0.1 - Includes ICP (Default Install Image) - Linux x86 Multiplatform Multilingual (CC2H0ML )

The correct part number should be CC356ML.
IBM Cloud Pak for Data Enterprise Edition V2.1.0.2-requires pre-existing ICP (Default Install Image) Linux x86 Multiplatform Multilingual (CC356ML )

**Comment by msochka** [comment]
No clients are currently on this release and we're removing the documentation from production.
