### ISSUE TITLE
Prohibited term: master

### ISSUE THREAD

**Issue by cdmauney** [ibm-cloud-docs/ai-openscale-icp#37]
Do not use. Use another term such as "controller," "leader," "parent," or "primary."

https://cloud.ibm.com/docs/ai-openscale-icp?topic=ai-openscale-icp-inst-install-icp

**Comment by msochka** [comment]
@cdmauney 

I've updated the docs. Please close this issue after you verify. Thanks.

**Comment by cdmauney** [comment]
Verified. Thanks!
